# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Shb7j8kfLGBxIYyW80sQB6KwSWdAmU1
"""

import random
subject= ["MS DHONI", "Virat Kohli", "president", "groom", "bride", "indian cat", "badminton", "cab drivers"]
actions= ["launches", "makes", "declares", "creates", "eats", "plays", "drinks", "dances", "manages", "publishes", "says", "calls","celebrates"]
places_or_things= ["in dubai metro", "in the kitchen", "a plate of momos", "at the playground", "in the swimming pool", "bunch of grapes", "tomato ketchup" "orange juice"]
while True:
  subject = random.choice(subject)
  actions = random.choice(actions)
  places_or_things = random.choice(places_or_things)

  headline = f" Breaking News: {subject} {actions} {places_or_things}"
  print("\n" + headline)
  user_input= input("\n Do you want another headline? (yes/no)"). strip()
  if user_input == "no":
    break
print("\n Thanks for using News Headline Generator")